version: "3"
services:
  alpine:
    image: alpine:$ALPINE_IMG_TAG
    command: ["sleep", "infinity"]
  deployer:
    image: fatindeed/docker-compose-deployer
    ports:
      - 8000:8000
    environment:
      DEPLOYER_WORKDIR: /mnt/demo
      DEPLOYER_SECRET: your-256-bit-secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/mnt/demo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/ping"]